service: TodoDynamoDB
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  app:
    handler: build/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

      
